// Minimal shim of firebase_options.dart for CI/tests when real
// firebase configuration is not present. Replace this file with the
// Firebase CLI generated `firebase_options.dart` when configuring
// Firebase for each platform.
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  // Returns a minimal FirebaseOptions instance. Apps should replace
  // these placeholder values with real configuration generated by
  // `flutterfire configure`.
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
    apiKey: '',
    appId: '1:000:android:0000000000',
    messagingSenderId: '0000000000',
    projectId: 'your-project-id',
  );
}
